name: React Workflow v1.0 - [Beta]

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code from the repo
      - name: Checkout Code
        uses: actions/checkout@v2
        
      # Install Node.js (required for building the React app)
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          
      # Install dependencies and build the React app
      - name: Install React App Dependencies
        run: |
          npm install
      - name: Build React App
        run: |
          npm run build --if-present
          
      # Configure git user
      - name: Configure Git User
        env:
        # Your Name For Commit
          GIT_USERNAME: USERNAME
        # Your Email For Commit
          GIT_USEREMAIL: EMAIL
        run: |
          git config --local user.name "${GIT_USERNAME}"
          git config --local user.email "${GIT_USEREMAIL}"
      
      # Copy the built files to the gh-pages branch
      - name: Copy Built Files to gh-pages Branch
        run: |
          mkdir -p .deploy
          mv build/* .deploy/
          git checkout -b gh-pages || git branch gh-pages
          rsync -av .deploy/ .
          
      # Commit the changes to the gh-pages branch
      - name: Commit Changes to gh-pages Branch
        run: |
          git pull --rebase origin gh-pages
          git add .
          git commit -m "Build and deploy React app to gh-pages"
          git push --set-upstream origin gh-pages
          